from flask import Blueprint, jsonify, request, abort
from main import db
from models.diaries import Diary
from models.users import User
from schemas.diary_schema import diary_schema, diaries_schema
from schemas.diary_schema import DiarySchema
from datetime import date
from flask_jwt_extended import jwt_required, get_jwt_identity


diaries = Blueprint('diaries', __name__, url_prefix="/diaries")

# Route for getting a diary entry: /diaries/<int:id>
@diaries.route("/<int:id>/", methods=["GET"])
@jwt_required()
def get_diary(id):
    stmt = db.select(Diary).filter_by(id=id)
    diary = db.session.scalar(stmt)
    #return an error if the diary doesn't exist
    if not diary:
        return abort(400, description= "Diary not found")
    # Convert the diaries from the database into a JSON format and store them in result
    result = diary_schema.dump(diary)
    # return the data in JSON format
    return jsonify(result)

# Route for getting diary entries from a particular user /diaries/user
@diaries.route("/user", methods = ["GET"])
@jwt_required()
def get_user_diary(): 
    user_id = get_jwt_identity()

    stmt = db.select(Diary).filter_by(user_id = user_id)
    diaries = db.session.scalars(stmt)

    result = diaries_schema.dump(diaries)
    return jsonify(result)

# Route to post diary entry /

@diaries.route("/", methods=["POST"])
@jwt_required()
def create_diary():
    # #Create a new card
    diary_fields = diary_schema.load(request.json)

    # get the id from jwt
    user_id = get_jwt_identity()
    new_diary = Diary()
    new_diary.title = diary_fields["title"]
    new_diary.description = diary_fields["description"]
    # not taken from the request, generated by the server
    new_diary.date = date.today()
    # Use that id to set the ownership of the card
    new_diary.user_id = user_id
    # add to the database and commit
    db.session.add(new_diary)
    db.session.commit()
 
    return jsonify(diary_schema.dump(new_diary))